name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 

      - name: Build the Docker image
        run: docker build -t hariharansdeveloper/online-compiler-frontend:latest .

      - name: Push to Docker Hub
        run: docker push hariharansdeveloper/online-compiler-frontend:latest
